### ISSUE TITLE
prepare_data中代码确认

### ISSUE THREAD

**Issue by pekingzlj** [CAN-Paper/Co-Action-Network#3]
你好！请问prepare_data.sh 代码中
gunzip reviews_Books.json.gz
gunzip meta_Books.json.gz
python script/process_data.py meta_Books.json reviews_Books_5.json

解压reviews_Books.json.gz得到的是reviews_Books.json，而 script/process_data.py传入的参数是 reviews_Books_5.json。请问reviews_Books_5.json即是reviews_Books.json文件吗。多谢了。

**Comment by CAN-Paper** [comment]
对的，该部分代码沿用了[DIEN](https://github.com/mouna99/dien)，会fix一下

**Comment by bigbigda** [comment]
似乎一直没有修复：）

> 对的，该部分代码沿用了[DIEN](https://github.com/mouna99/dien)，会fix一下
